# ---- Step 1: Build Angular App ----
FROM node:22 AS build-stage

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npx ng build --configuration=docker

# ---- Step 2: Serve with NGINX ----
FROM nginx:1.25

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build-stage /app/dist/frontend/browser/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]