FROM node:22 AS build-stage

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install  # Ensures node_modules is correctly installed

COPY . .

RUN npx ng build --configuration=docker

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--configuration=docker"]
