services:
  backend:
    container_name: jobseeker-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.app
    environment:
      - FLASK_ENV=production
      - MYSQL_HOST=host.docker.internal 
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=jobspy
      - MYSQL_USER=jobspy
      - MYSQL_PASSWORD=jobspy
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - mainNetwork

  batch:
    container_name: jobseeker-batch
    build:
      context: ./backend
      dockerfile: Dockerfile.batch
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=jobspy
      - MYSQL_USER=jobspy
      - MYSQL_PASSWORD=jobspy
    restart: unless-stopped
    networks:
      - mainNetwork

  frontend:
    container_name: jobseeker-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=jobspy
      - MYSQL_USER=jobspy
      - MYSQL_PASSWORD=jobspy
    restart: unless-stopped
    networks:
      - mainNetwork
networks:
  mainNetwork:
  