name: jobseeker
services:
  backend:
    container_name: jobseeker-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.app
    environment:
      - FLASK_ENV=production
      - MYSQL_HOST=host.docker.internal 
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=jobspy
      - MYSQL_USER=jobspy
      - MYSQL_PASSWORD=jobspy
      - PORT=6081
    ports:
      - "6081:6081"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - mainNetwork

  batch:
    container_name: jobseeker-batch
    build:
      context: ./backend
      dockerfile: Dockerfile.batch
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=jobspy
      - MYSQL_USER=jobspy
      - MYSQL_PASSWORD=jobspy
    restart: unless-stopped
    networks:
      - mainNetwork

  frontend:
    container_name: jobseeker-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "6080:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - mainNetwork
networks:
  mainNetwork:
  