"""initial migration

Revision ID: 5a8ab22ba728
Revises: 
Create Date: 2025-01-24 16:33:05.699127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a8ab22ba728'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobposts', schema=None) as batch_op:
        batch_op.alter_column('site_id',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('site',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('company',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('company_url',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('job_url',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=1000, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('location_country',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('location_city',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('location_state',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(collation='armscii8_bin'),
               type_=sa.Text(collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('job_function_interval',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('job_function_currency',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('job_function_salary_source',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('emails',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=1000),
               type_=sa.String(length=1000, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('job_level',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('company_industry',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('company_country',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('company_addresses',
               existing_type=mysql.TEXT(collation='armscii8_bin'),
               type_=sa.Text(collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('company_employees_label',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('company_revenue_label',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('company_description',
               existing_type=mysql.TEXT(collation='armscii8_bin'),
               type_=sa.Text(collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('company_logo',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=1000),
               type_=sa.String(length=1000, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'jobqueries', ['jobquery_id'], ['id'])

    with op.batch_alter_table('jobqueries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('search_term',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=100),
               type_=sa.String(length=100, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('town',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=255),
               type_=sa.String(length=255, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=100),
               type_=sa.String(length=100, collation='utf8_bin'),
               existing_nullable=True,
               existing_server_default=sa.text("'BE'"))
        batch_op.alter_column('filters',
               existing_type=mysql.VARCHAR(collation='armscii8_bin', length=500),
               type_=sa.String(length=1000, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.drop_column('createdAt')
        batch_op.drop_column('updatedAt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobqueries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('createdAt', mysql.DATETIME(), nullable=False))
        batch_op.alter_column('filters',
               existing_type=sa.String(length=1000, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=500),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.String(length=100, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'BE'"))
        batch_op.alter_column('town',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('search_term',
               existing_type=sa.String(length=100, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('jobposts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('company_logo',
               existing_type=sa.String(length=1000, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=1000),
               existing_nullable=True)
        batch_op.alter_column('company_description',
               existing_type=sa.Text(collation='utf8_bin'),
               type_=mysql.TEXT(collation='armscii8_bin'),
               existing_nullable=True)
        batch_op.alter_column('company_revenue_label',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('company_employees_label',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('company_addresses',
               existing_type=sa.Text(collation='utf8_bin'),
               type_=mysql.TEXT(collation='armscii8_bin'),
               existing_nullable=True)
        batch_op.alter_column('company_country',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('company_industry',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('job_level',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('emails',
               existing_type=sa.String(length=1000, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=1000),
               existing_nullable=True)
        batch_op.alter_column('job_function_salary_source',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('job_function_currency',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('job_function_interval',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(collation='utf8_bin'),
               type_=mysql.TEXT(collation='armscii8_bin'),
               existing_nullable=True)
        batch_op.alter_column('location_state',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('location_city',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('location_country',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('job_url',
               existing_type=sa.String(length=1000, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('company_url',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('company',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=False)
        batch_op.alter_column('site',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('site_id',
               existing_type=sa.String(length=255, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='armscii8_bin', length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
