"""JobUserStatus

Revision ID: 95932429182a
Revises: 5a8ab22ba728
Create Date: 2025-01-29 21:48:10.447039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95932429182a'
down_revision = '5a8ab22ba728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255, collation='utf8_bin'), nullable=True),
    sa.Column('capyx_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_user_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'viewed', 'starred', 'hidden', name='jobstatus'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobposts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobposts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('new', 'viewed', 'hidden', 'starred', charset='utf8', collation='utf8_bin'),
               type_=sa.Enum('new', 'viewed', 'starred', 'hidden', name='jobstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'new'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobposts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('new', 'viewed', 'starred', 'hidden', name='jobstatus'),
               type_=mysql.ENUM('new', 'viewed', 'hidden', 'starred', charset='utf8', collation='utf8_bin'),
               existing_nullable=True,
               existing_server_default=sa.text("'new'"))

    op.drop_table('job_user_status')
    op.drop_table('users')
    # ### end Alembic commands ###
